In [1]:
def outer_sum(a,b):
    return a[:, None] + b[None, :]
def less_equal(a, b):
    return (a[:, None] <= b[None, :])
def less(a, b):
    return (a[:, None] < b[None, :])
def equal(a, b):
    return (a[:, None] == b[None, :])

In [2]:
import numpy as np
masses = np.array([
    1,
    2,
    3,
    1,
    2,
]).astype(float)

In [3]:
collision_matrix = np.array([
    [1,1,0,0,0],
    [1,1,1,0,0],
    [0,1,1,1,0],
    [0,0,1,1,1],
    [0,0,0,1,1],
]).astype(bool)
np.fill_diagonal(collision_matrix,False)

In [4]:
'''
5 objects collide at the same time

obj#:  1    2    3    4    5
mass: (1)->(2)->(3)<-(1)->(2) 
           (3)->(4)       (2)
2 absorbs 1
3 absorbs 4

'''

'\n5 objects collide at the same time\n\nobj#:  1    2    3    4    5\nmass: (1)->(2)->(3)<-(1)->(2) \n           (3)->(4)       (2)\n2 absorbs 1\n3 absorbs 4\n\n'

In [20]:
positions = np.array([
    [0,0,0],
    [1,0,0],
    [2,0,0],
    [3,0,0],
    [4,0,0],
])

In [5]:
masses

array([1., 2., 3., 1., 2.])

In [10]:
m_less = less(masses, masses)
m_equal= np.tril(equal(masses, masses),-1)

In [11]:
# Absorbtion matrix
absorbed_matrix = (m_less+m_equal)*collision_matrix
absorbed_matrix.astype(int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0]])

In [12]:
# Each object can only be absorbed once; choose the first absorber
absorbed_matrix_mod = absorbed_matrix.cumsum(axis=1).cumsum(axis=1) == 1
absorbed_matrix_mod.astype(int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
# All objects absorbing
absorbing = np.max(absorbed_matrix_mod, axis=0)
absorbing.astype(int)

array([0, 1, 1, 0, 0])

In [14]:
# Can only be absorbed if you are not also absorbing
absorbed_matrix_final = (absorbed_matrix_mod.T*(~absorbing)).T
absorbed = np.max(absorbed_matrix_final, axis=1)

In [15]:
absorbed

array([ True, False, False,  True, False])

In [16]:
absorbing

array([False,  True,  True, False, False])

In [25]:
m_totals = outer_sum(masses, masses)
m_totals

array([[2., 3., 4., 2., 3.],
       [3., 4., 5., 3., 4.],
       [4., 5., 6., 4., 5.],
       [2., 3., 4., 2., 3.],
       [3., 4., 5., 3., 4.]])

In [23]:
moments = masses[:,None] * positions
moments

array([[0., 0., 0.],
       [2., 0., 0.],
       [6., 0., 0.],
       [3., 0., 0.],
       [8., 0., 0.]])

In [35]:
new_positions = outer_sum(moments, moments)/m_totals[None,:].T
new_positions

array([[[0.        , 0.        , 0.        ],
        [0.66666667, 0.        , 0.        ],
        [1.5       , 0.        , 0.        ],
        [1.5       , 0.        , 0.        ],
        [2.66666667, 0.        , 0.        ]],

       [[0.66666667, 0.        , 0.        ],
        [1.        , 0.        , 0.        ],
        [1.6       , 0.        , 0.        ],
        [1.66666667, 0.        , 0.        ],
        [2.5       , 0.        , 0.        ]],

       [[1.5       , 0.        , 0.        ],
        [1.6       , 0.        , 0.        ],
        [2.        , 0.        , 0.        ],
        [2.25      , 0.        , 0.        ],
        [2.8       , 0.        , 0.        ]],

       [[1.5       , 0.        , 0.        ],
        [1.66666667, 0.        , 0.        ],
        [2.25      , 0.        , 0.        ],
        [3.        , 0.        , 0.        ],
        [3.66666667, 0.        , 0.        ]],

       [[2.66666667, 0.        , 0.        ],
        [2.5       , 0.   

In [43]:
absorbed_matrix_final.astype(int)

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]])

In [63]:
new_positions_abs = new_positions*(absorbed_matrix_final.T.reshape(5,5,1))
new_positions_abs

array([[[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]],

       [[0.66666667, 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [2.25      , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        ]],

       [[0.        , 0.        , 0.        ],
        [0.        , 0.   

In [121]:
mask = np.expand_dims(~absorbed_matrix_final.T, axis=2)
mask.astype(int)

array([[[1],
        [1],
        [1],
        [1],
        [1]],

       [[0],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [0],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [1],
        [1]]])

In [122]:
mask_vec = np.repeat(mask, 3, axis=2)
mask_vec.astype(int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[0, 0, 0],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [0, 0, 0],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [127]:
np.putmask(new_positions, mask_vec, None)
new_positions_final = np.nanmean(new_positions, axis=1)
new_positions_final

C:\Users\joeto\AppData\Local\Temp\ipykernel_2260\7387813.py:2: RuntimeWarning: Mean of empty slice
  new_positions_final = np.nanmean(new_positions, axis=1)


array([[       nan,        nan,        nan],
       [0.66666667, 0.        , 0.        ],
       [2.25      , 0.        , 0.        ],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan]])

In [128]:
pfinal = np.copy(positions).astype(float)
pfinal[absorbing] = new_positions_final[absorbing]
pfinal

array([[0.        , 0.        , 0.        ],
       [0.66666667, 0.        , 0.        ],
       [2.25      , 0.        , 0.        ],
       [3.        , 0.        , 0.        ],
       [4.        , 0.        , 0.        ]])

In [133]:
m_totals

array([[2., 3., 4., 2., 3.],
       [3., 4., 5., 3., 4.],
       [4., 5., 6., 4., 5.],
       [2., 3., 4., 2., 3.],
       [3., 4., 5., 3., 4.]])

In [134]:
~absorbed_matrix_final.T

array([[ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [136]:
masses*absorbed_matrix_final.T

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [137]:
import random

In [139]:
f"-{random.randint(1,1000)}"

'-964'

In [140]:
absorbing

array([False,  True,  True, False, False])

In [142]:
~absorbed

array([False,  True,  True, False,  True])

In [144]:
absorbing & ~absorbed

array([False,  True,  True, False, False])

In [145]:
absorbing & np.array([False, True, False, False, True])

array([False,  True, False, False, False])

In [146]:
absorbed_matrix_mod

array([[False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])