In [7]:
def outer_sum(a,b):
    return a[:, None] + b[None, :]
def less_equal(a, b):
    return (a[:, None] <= b[None, :])
def less(a, b):
    return (a[:, None] < b[None, :])
def equal(a, b):
    return (a[:, None] == b[None, :])

In [71]:
import numpy as np
masses = np.array([
    1,
    2,
    3,
    1,
    2,
]).astype(float)

In [72]:
collision_matrix = np.array([
    [1,1,0,0,0],
    [1,1,1,0,0],
    [0,1,1,1,0],
    [0,0,1,1,1],
    [0,0,0,1,1],
]).astype(bool)
np.fill_diagonal(collision_matrix,False)

In [ ]:
'''
5 objects collide at the same time

obj#:  1    2    3    4    5
mass: (1)->(2)->(3)<-(1)->(2) 
           (3)->(4)       (2)
2 absorbs 1
3 absorbs 4

'''

In [73]:
masses

array([1., 2., 3., 1., 2.])

In [74]:
m_less = less(masses, masses)
m_equal= np.tril(equal(masses, masses),-1)

In [75]:
absorbed_matrix = (m_less+m_equal)*collision_matrix
absorbed_matrix

array([[False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False,  True, False,  True],
       [False, False, False, False, False]])

In [81]:
absorbed_matrix_mod = absorbed_matrix.cumsum(axis=1).cumsum(axis=1) == 1 #Only get absorbed by first object
absorbed_matrix_mod

array([[False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [76]:
absorbing_matrix = ~(m_less+m_equal)*collision_matrix
absorbing_matrix

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False,  True, False,  True, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [84]:
absorbed_matrix_mod * absorbing_matrix.T

array([[False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [77]:
absorbed = np.max(absorbed_matrix, axis=1)#.nonzero()[0].tolist()
absorbed

array([ True,  True, False,  True, False])

In [78]:
absorbed_mass_matrix = masses*absorbed_matrix.T
absorbed_mass_matrix

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]])