In [71]:
import numpy as np

positions = np.array([
    [0,0,0],
    [1,0,0],
    [-1,0,0],
    [0,1,0],
    [0,-1,0]
])

densities = np.array([
    3,
    4,
    5,
    6,
    7
])

masses = np.array([
    5,
    2,
    1,
    2,
    1,
])

In [13]:
moments = masses[:,None] * positions

In [34]:
moments.shape

(5, 3)

In [56]:
moments

array([[ 0,  0,  0],
       [ 2,  0,  0],
       [-1,  0,  0],
       [ 0,  2,  0],
       [ 0, -1,  0]])

In [65]:
m_totals = np.add.outer(masses, masses)

In [103]:
m_greater = np.greater_equal.outer(masses, masses)
m_greater

array([[ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True, False,  True],
       [False,  True,  True,  True,  True],
       [False, False,  True, False,  True]])

In [77]:
coms = (moments + moments[:, None, :])/m_totals[None,:].T
coms

array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.28571429,  0.        ,  0.        ],
        [-0.16666667,  0.        ,  0.        ],
        [ 0.        ,  0.28571429,  0.        ],
        [ 0.        , -0.16666667,  0.        ]],

       [[ 0.28571429,  0.        ,  0.        ],
        [ 1.        ,  0.        ,  0.        ],
        [ 0.33333333,  0.        ,  0.        ],
        [ 0.5       ,  0.5       ,  0.        ],
        [ 0.66666667, -0.33333333,  0.        ]],

       [[-0.16666667,  0.        ,  0.        ],
        [ 0.33333333,  0.        ,  0.        ],
        [-1.        ,  0.        ,  0.        ],
        [-0.33333333,  0.66666667,  0.        ],
        [-0.5       , -0.5       ,  0.        ]],

       [[ 0.        ,  0.28571429,  0.        ],
        [ 0.5       ,  0.5       ,  0.        ],
        [-0.33333333,  0.66666667,  0.        ],
        [ 0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.33333333,  0.        ]],

       [[ 0.

In [99]:
collision_matrix = np.array([
    [1,0,0,0,0],
    [0,1,0,0,0],
    [0,0,1,1,0],
    [0,0,1,1,0],
    [0,0,0,0,1],
])
np.fill_diagonal(collision_matrix,0)
collision_matrix

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0]])

In [100]:
coms_masked = collision_matrix.reshape(5,5,1)*coms

In [101]:
coms_masked

array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        , -0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        , -0.        ,  0.        ]],

       [[-0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [-0.        ,  0.        ,  0.        ],
        [-0.33333333,  0.66666667,  0.        ],
        [-0.        , -0.        ,  0.        ]],

       [[ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [-0.33333333,  0.66666667,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[ 0.

0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
